"""Descrição da migration

Revision ID: 560a5af47dfd
Revises: 
Create Date: 2025-07-01 20:07:32.750476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560a5af47dfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_data', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_column('basic_data', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_data', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('basic_data', 'uid')
    # ### end Alembic commands ###
