"""Descrição da migration

Revision ID: e6cd4b00d140
Revises: 560a5af47dfd
Create Date: 2025-07-02 09:23:19.719979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cd4b00d140'
down_revision: Union[str, Sequence[str], None] = '560a5af47dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_data', sa.Column('firstName', sa.String(), nullable=False))
    op.add_column('basic_data', sa.Column('lastName', sa.String(), nullable=False))
    op.drop_column('basic_data', 'firstname')
    op.drop_column('basic_data', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_data', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('basic_data', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('basic_data', 'lastName')
    op.drop_column('basic_data', 'firstName')
    # ### end Alembic commands ###
